const MODELS = [
  { id: "glm-5.2", name: "GLM-5.2" },
  { id: "glm-5.1", name: "GLM-5.1" },
  { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
  { id: "kimi-k2.6", name: "Kimi K2.6" },
  { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
  { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
  { id: "mimo-v2.5-pro", name: "MiMo-V2.5-Pro" },
  { id: "mimo-v2.5", name: "MiMo-V2.5" },
];

module.exports = {
  id: "opencode-go-openai",
  name: "OpenCode Go (OpenAI-compatible)",
  adapter: "openai-compatible",
  apiKeyEnv: ["OPENCODE_API_KEY"],
  baseUrlEnv: ["OPENCODE_GO_BASE_URL"],
  openaiCompatible: {
    bodyExtensions: {},
  },
  settingsSchema: [
    {
      key: "temperature",
      label: "Temperature",
      type: "range",
      min: 0,
      max: 2,
      step: 0.1,
      decimals: 1,
      capability: "temperature",
    },
    {
      key: "topP",
      label: "Top P",
      type: "range",
      min: 0,
      max: 1,
      step: 0.05,
      decimals: 2,
      capability: "topP",
    },
    {
      key: "maxOutputTokens",
      label: "Max Output Tokens",
      type: "number",
      min: 128,
      max: 128000,
      step: 1024,
      capability: "maxTokens",
    },
    {
      key: "stream",
      label: "Streaming",
      type: "toggle",
      capability: "stream",
    },
  ],
  models: MODELS,
  parameterPolicy: {
    blockedBodyParams: [
      "presence_penalty",
      "frequency_penalty",
      "tools",
      "tool_choice",
      "parallel_tool_calls",
    ],
  },
  capabilities: {
    stream: true,
    temperature: true,
    topP: true,
    maxTokens: true,
    presencePenalty: false,
    frequencyPenalty: false,
    webSearch: false,
    tools: false,
    thinking: false,
  },
};
